export default function Screen() {
    return (
        <div className="screen">
            <ol>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
                <li>shalom</li>
            </ol>
        </div>
    );
}
